// <auto-generated />
using System;
using HireMeApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HireMeApi.Data.Migrations
{
    [DbContext(typeof(HireMeApiDbContext))]
    partial class HireMeApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("HireMeApi.Domain.Models.IotDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IotDevices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("716b049d-ea56-4be9-beb4-872e92309e08"),
                            Name = "Device 1"
                        },
                        new
                        {
                            Id = new Guid("740ed1aa-24d6-47f7-89f4-918833c93d94"),
                            Name = "Device 2"
                        },
                        new
                        {
                            Id = new Guid("8d824a3a-5c14-4d0e-9f6d-8e2f3f8eac44"),
                            Name = "Device 3"
                        },
                        new
                        {
                            Id = new Guid("997bfeb4-fc99-4cae-9b5a-5fd194ebd302"),
                            Name = "Device 4"
                        },
                        new
                        {
                            Id = new Guid("34357646-4c66-4f48-b9ef-55a112d2564a"),
                            Name = "Device 5"
                        },
                        new
                        {
                            Id = new Guid("03ed13c4-9e7c-4b74-9d8b-b88c63b8feb6"),
                            Name = "Device 6"
                        },
                        new
                        {
                            Id = new Guid("4c1c23cd-cf06-4d5f-9491-a1733651ea7a"),
                            Name = "Device 7"
                        },
                        new
                        {
                            Id = new Guid("22147ae1-60ec-4bcb-a601-bc133d5a8c8c"),
                            Name = "Device 8"
                        },
                        new
                        {
                            Id = new Guid("1118aff0-b4be-40bc-a1c5-03cf037927a8"),
                            Name = "Device 9"
                        },
                        new
                        {
                            Id = new Guid("0241c522-260c-4342-a99e-d4b375f9c2ee"),
                            Name = "Device 10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
